config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  resources :events
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   end

    resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validates :duration, numericality: { greater_than_or_equal_to: 0 }
  validates :title, length: {in: 5..140 }
  validates :description, length: {in: 2..1000 }
  validates :price, length: {in: 1..1000 }
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  
  has_many :attendances
  has_many :events, through: :attendances

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<h3>
  Liste des événements :

  <table class="table table-bordered">
  <thead>
    <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <td>Lieu</td>
  </tr>
  <br>
  <% @event.each do |event| %>
   
    <tr>
      <td><%= event.id %></td>
      <td><%= event.title %> </td>
      <td><%= event.start_date %></td>
      <td><%= event.location %></td>
      <td><%= link_to " Voir l'événement", event_path(event) %></td>
    </tr>
    
  <% end %>
  </tr>
  </tbody>
</table>
<br><br>
<%= link_to "Créer un nouvel événement", '/events/new' %>



     
   

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <div class="collapse navbar-collapse" id="navbarNav" >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_event_path %>">Create an event</a>
        </li>
        
        
        <% if current_user %>
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
      <div class="btn-group" role="group">
          <li class="nav-item"><a style="color: green;" href="/users/<%= current_user.id %>"  class="btn btn-sm btn-outline-secondary">My Profile</a></li>
          <li class="nav-item"><a style="color: green;" href="<%= destroy_user_session_path %>"  class="btn btn-sm btn-outline-secondary">Log out</a></li>
          </div>
      </div>
    </div>

    
    <% else %>
      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
              <li class="nav-item"><a style="color: green;" href="<%= new_user_registration_path %>"  class="btn btn-sm btn-outline-secondary">Sign up</a></li>
              <li class="nav-item"><a style="color: green;" href="<%= new_user_session_path %>"  class="btn btn-sm btn-outline-secondary">Login</a></li>
              </div>
        </div>
      </div>
    <% end %>
</nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">

<div class="row">









<div class="col">
<div class="card mb-4" style="width: 17rem; height: 12rem;">
  <div class="card-body">
  <h5 class="card-title"><%= User.find_by(id: @user.id).name  %>  </h5>
  <h6 class="card-subtitle mb-2 text-muted"><%= User.find_by(id: @user.id).email  %></h6>

  <h8 class="card-subtitle mb-2 text-muted">Description :<%= User.find_by(id: @user.id).description %></h8>
 
 <div class="btn-group">
 <a href="<%=root_path%>" class="btn btn-light"> Return Home</a>

 </a>


      </div>
   
     
      

  </div>
 </div>
</div>

</div>
</div>
</div>

</div>